### ISSUE TITLE
Wrong main field in package.json

### ISSUE THREAD

**Issue by felixroos** [d0kt0r0/WebDirt#13]
When installing the repo with npm, imports fail because index.js does not exist but is declared as main file in package.json. I think js-src/WebDirt.js should be the main file. Should I send a PR?

**Comment by dktr0** [comment]
Sure, I haven't had the chance to look at anything to do with npm and webdirt, so anything that helps make it more useful in various ways would be appreciated.

**Comment by felixroos** [comment]
PR is out
